package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"firebase.google.com/go"
	"google.golang.org/api/option"
)

type AutoGenerated struct {
	A []struct {
		B struct {
			Title                         string `json:"title"`
			INDEX                         string `json:"INDEX"`
			DEADEND                       string `json:"DEAD_END"`
			Q01IschemicSymptoms           string `json:"Q01 - Ischemic Symptoms"`
			Q02AntiIschemicMedicalTherapy string `json:"Q02 - Anti-ischemic Medical Therapy:"`
			Q03NonInvasiveTestResults     string `json:"Q03 - Non-invasive Test Results:"`
			Q04PRIORCABG                  string `json:"Q04 - PRIOR CABG"`
			Q01                           string `json:"Q01"`
			Q02                           string `json:"Q02"`
			Q03                           string `json:"Q03"`
			Q04                           string `json:"Q04"`
			E01PRIMARY                    string `json:"E01 PRIMARY"`
			E01CABG                       string `json:"E01 CABG"`
			E01PCI                        string `json:"E01 PCI"`
			E02PRIMARY                    string `json:"E02 PRIMARY"`
			E02CABG                       string `json:"E02 CABG"`
			E02PCI                        string `json:"E02 PCI"`
			E03PRIMARY                    string `json:"E03 PRIMARY"`
			E03CABG                       string `json:"E03 CABG"`
			E03PCI                        string `json:"E03 PCI"`
			E04PRIMARY                    string `json:"E04 PRIMARY"`
			E04CABG                       string `json:"E04 CABG"`
			E04PCI                        string `json:"E04 PCI"`
			E05PRIMARY                    string `json:"E05 PRIMARY"`
			E05CABG                       string `json:"E05 CABG "`
			E05PCI                        string `json:"E05 PCI"`
			E05APRIMARY                   string `json:"E05a PRIMARY"`
			E05ACABG                      string `json:"E05a CABG"`
			E05APCI                       string `json:"E05a PCI"`
			E05BPRIMARY                   string `json:"E05b PRIMARY"`
			E05BCABG                      string `json:"E05b CABG"`
			E05BPCI                       string `json:"E05b PCI"`
			E05CPRIMARY                   string `json:"E05c PRIMARY"`
			E05CCABG                      string `json:"E05c CABG"`
			E05CPCI                       string `json:"E05c PCI"`
			E06PRIMARY                    string `json:"E06 PRIMARY"`
			E06CABG                       string `json:"E06 CABG"`
			E06PCI                        string `json:"E06 PCI"`
			E06APRIMARY                   string `json:"E06a PRIMARY"`
			E06ACABG                      string `json:"E06a CABG"`
			E06APCI                       string `json:"E06a PCI"`
			E06BPRIMARY                   string `json:"E06b PRIMARY"`
			E06BCABG                      string `json:"E06b CABG"`
			E06BPCI                       string `json:"E06b PCI"`
			E06CPRIMARY                   string `json:"E06c PRIMARY"`
			E06CCABG                      string `json:"E06c CABG"`
			E06CPCI                       string `json:"E06c PCI"`
			E07PRIMARY                    string `json:"E07 PRIMARY"`
			E07CABG                       string `json:"E07 CABG"`
			E07PCI                        string `json:"E07 PCI"`
			E07APRIMARY                   string `json:"E07a PRIMARY"`
			E07ACABG                      string `json:"E07a CABG"`
			E07APCI                       string `json:"E07a PCI"`
			E07BPRIMARY                   string `json:"E07b PRIMARY"`
			E07BCABG                      string `json:"E07b CABG"`
			E07BPCI                       string `json:"E07b PCI"`
			E07CPRIMARY                   string `json:"E07c PRIMARY"`
			E07CCABG                      string `json:"E07c CABG"`
			E07CPCI                       string `json:"E07c PCI"`
			F01PRIMARY                    string `json:"F01 PRIMARY"`
			F02PRIMARY                    string `json:"F02 PRIMARY"`
			F03PRIMARY                    string `json:"F03 PRIMARY"`
			F03CABGPCI                    string `json:"F03 CABG PCI"`
			F03CABG                       string `json:"F03 CABG"`
			F03PCI                        string `json:"F03 PCI"`
			F04PRIMARY                    string `json:"F04 PRIMARY"`
			F04CABGPCI                    string `json:"F04 CABG PCI"`
			F04CABG                       string `json:"F04 CABG"`
			F04PCI                        string `json:"F04 PCI"`
		} `json:"b"`
	} `json:"a"`
}

type NONACS struct {
	Title                         string `json:"title"`
	INDEX                         string `json:"INDEX"`
	DEADEND                       string `json:"DEAD_END"`
	Q01IschemicSymptoms           string `json:"Q01 - Ischemic Symptoms"`
	Q02AntiIschemicMedicalTherapy string `json:"Q02 - Anti-ischemic Medical Therapy:"`
	Q03NonInvasiveTestResults     string `json:"Q03 - Non-invasive Test Results:"`
	Q04PRIORCABG                  string `json:"Q04 - PRIOR CABG"`
	Q01                           string `json:"Q01"`
	Q02                           string `json:"Q02"`
	Q03                           string `json:"Q03"`
	Q04                           string `json:"Q04"`
	E01PRIMARY                    string `json:"E01 PRIMARY"`
	E01CABG                       string `json:"E01 CABG"`
	E01PCI                        string `json:"E01 PCI"`
	E02PRIMARY                    string `json:"E02 PRIMARY"`
	E02CABG                       string `json:"E02 CABG"`
	E02PCI                        string `json:"E02 PCI"`
	E03PRIMARY                    string `json:"E03 PRIMARY"`
	E03CABG                       string `json:"E03 CABG"`
	E03PCI                        string `json:"E03 PCI"`
	E04PRIMARY                    string `json:"E04 PRIMARY"`
	E04CABG                       string `json:"E04 CABG"`
	E04PCI                        string `json:"E04 PCI"`
	E05PRIMARY                    string `json:"E05 PRIMARY"`
	E05CABG                       string `json:"E05 CABG "`
	E05PCI                        string `json:"E05 PCI"`
	E05APRIMARY                   string `json:"E05a PRIMARY"`
	E05ACABG                      string `json:"E05a CABG"`
	E05APCI                       string `json:"E05a PCI"`
	E05BPRIMARY                   string `json:"E05b PRIMARY"`
	E05BCABG                      string `json:"E05b CABG"`
	E05BPCI                       string `json:"E05b PCI"`
	E05CPRIMARY                   string `json:"E05c PRIMARY"`
	E05CCABG                      string `json:"E05c CABG"`
	E05CPCI                       string `json:"E05c PCI"`
	E06PRIMARY                    string `json:"E06 PRIMARY"`
	E06CABG                       string `json:"E06 CABG"`
	E06PCI                        string `json:"E06 PCI"`
	E06APRIMARY                   string `json:"E06a PRIMARY"`
	E06ACABG                      string `json:"E06a CABG"`
	E06APCI                       string `json:"E06a PCI"`
	E06BPRIMARY                   string `json:"E06b PRIMARY"`
	E06BCABG                      string `json:"E06b CABG"`
	E06BPCI                       string `json:"E06b PCI"`
	E06CPRIMARY                   string `json:"E06c PRIMARY"`
	E06CCABG                      string `json:"E06c CABG"`
	E06CPCI                       string `json:"E06c PCI"`
	E07PRIMARY                    string `json:"E07 PRIMARY"`
	E07CABG                       string `json:"E07 CABG"`
	E07PCI                        string `json:"E07 PCI"`
	E07APRIMARY                   string `json:"E07a PRIMARY"`
	E07ACABG                      string `json:"E07a CABG"`
	E07APCI                       string `json:"E07a PCI"`
	E07BPRIMARY                   string `json:"E07b PRIMARY"`
	E07BCABG                      string `json:"E07b CABG"`
	E07BPCI                       string `json:"E07b PCI"`
	E07CPRIMARY                   string `json:"E07c PRIMARY"`
	E07CCABG                      string `json:"E07c CABG"`
	E07CPCI                       string `json:"E07c PCI"`
	F01PRIMARY                    string `json:"F01 PRIMARY"`
	F02PRIMARY                    string `json:"F02 PRIMARY"`
	F03PRIMARY                    string `json:"F03 PRIMARY"`
	F03CABGPCI                    string `json:"F03 CABG PCI"`
	F03CABG                       string `json:"F03 CABG"`
	F03PCI                        string `json:"F03 PCI"`
	F04PRIMARY                    string `json:"F04 PRIMARY"`
	F04CABGPCI                    string `json:"F04 CABG PCI"`
	F04CABG                       string `json:"F04 CABG"`
	F04PCI                        string `json:"F04 PCI"`
}

func (p AutoGenerated) toString() string {
	return toJson(p)
}

//===================================================================
func toJson(p interface{}) string {
	bytes, err := json.Marshal(p)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	return string(bytes)
}

//===================================================================

//===================================================================
func main() {
	fmt.Println("===============================================")

	var newNONACS NONACS
	//ctx = context.Background()
	sa := option.WithCredentialsFile("./SQADMINSDK.json")
	app, err := firebase.NewApp(context.Background(), nil, sa)
	if err != nil {
		log.Fatal(err)
	}
	client2, err := app.Firestore(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	pages := getPages()
	for _, p := range pages.A {
		//fmt.Println(p.B.INDEX)
		fmt.Println("===============================================")
		fmt.Println(p.B)
		newNONACS = p.B
		fmt.Println("============aaaaaaaaaaaaa=====================")
		fmt.Println(newNONACS.INDEX)
		fmt.Println("===============================================")
		fmt.Println("=========  /////////////////////// ==========")

		_, err := client2.Collection("NONACSv01").Doc(newNONACS.INDEX).Set(context.Background(), newNONACS)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println("=========  /////////////////////// ==========")

		_, err = client2.Collection("NONACSv01_byTitle").Doc(newNONACS.Title).Set(context.Background(), newNONACS)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println("=========  /////////////////////// ==========")

	}
	defer client2.Close()

}

//===================================================================

//===================================================================
func getPages() AutoGenerated {
	raw, err := ioutil.ReadFile("./nonACS.json")
	if err != nil {
		fmt.Print("=========  error in Collection ==========")
		fmt.Println(err.Error())
		log.Fatal(err)
		os.Exit(1)
	}

	var c AutoGenerated
	json.Unmarshal(raw, &c)
	return c
}
